### PR TITLE
Feature/safety

### PR DESCRIPTION
**Pull request by glvr182**
Some safety improvements

Once the reviews are in I'll merge it

### CODE REVIEW

**Comment by mjarkk** [comment]
Nice PR, I’ll review it later today

**Comment by glvr182** [comment]
Updated to latest master

**Review by mjarkk — APPROVED** [review]
LGTM,  

I'm personally not a to big of a fan of defering a `sync.Mutex` because it usually delays the unblocking by a little bit what over a LOTS of updates might have some slowness and i think defering something is only needed when you have to write multiple times the same function before a return.  

But because the speed increase is so small if even there i don't think we have to change it, or you have to agree with my other point then we could change it.

**Comment by glvr182** [comment]
Interesting point, do you know of a more efficient way we could handle this?

**Comment by mjarkk** [comment]
```go
v.writeMutex.Lock()
// Fill with empty cells, if writing outside current view buffer
v.makeWriteable(v.wx, v.wy)
v.writeRunes(bytes.Runes(p))
v.writeMutex.Unlock()
```
It's not really shorter but you don't need the `defer`, and it's easier to read because you can read from top to bottom

**Comment by glvr182** [comment]
Fair enough, I shall refactor it

**Comment by glvr182** [comment]
I have updated it according to your suggestions @mjarkk

**Comment by skanehira** [comment]
LGTM :)

**Pull request merged**
